matrix:
  include:
    - language: java
      script:
        - cd backend && mvn clean test -Dmaven.javadoc.skip=true -Dspring.profiles.active=test -B -V
      addons:
        apt:
          packages:
            - oracle-java8-installer
      jdk: oraclejdk8
      sudo: false
      group: stable
      dist: precise
      os: linux
      notifications:
        email:
          on_success: never
          on_failure: always

    - language: node_js
      sudo: required
      dist: trusty
      node_js: stable
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
            - google-chrome-beta
      before_script:
          - npm install -g @angular/cli
          - cd frontend && npm install
          - export CHROME_BIN=chromium-browser
          - export DISPLAY=:99.0
          - sh -e /etc/init.d/xvfb start
      script: karma start karma.conf.js --single-run
      notifications:
        email:
          on_success: never # default: change
          on_failure: always # default: always
