matrix:
  include:
    - language: java
      script:
        - cd backend && mvn clean test -Dmaven.javadoc.skip=true -Dspring.profiles.active=test -B -V
      addons:
        apt:
          packages:
            - oracle-java8-installer
      jdk: oraclejdk8
      sudo: false
      group: stable
      dist: precise
      os: linux

    - language: node_js
      sudo: false
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
            - google-chrome-beta
        before_install:
          - export CHROME_BIN=chromium-browser
          - export DISPLAY=:99.0
          - sh -e /etc/init.d/xvfb start
        before_script:
          - npm install -g angular-cli
          - npm install karma --save-dev
          - npm install
          - ng build
      script: cd frontend && npm test
    - notifications:
        email: false
